### ISSUE TITLE
App freezes after pressing return 'X' number of times

### ISSUE THREAD

**Issue by gauravlnx** [JRG-Developer/AutoLayoutTextViews#5]
In my project, I noticed if a user presses the return 'X'(this count varies with layout) times with **ALAutoResizingTextView**, the app freezes. I have this layout setting for the text view:
1. Vertical center constraint to an ImageView.
2. Leading and Trailing constraints.
3. fixed height with 999 priority.
4. minimum height = 26
5. maximum height = 44

**Comment by JRG-Developer** [comment]
Can you provide a demo that shows this scenario?

I'd be happy to take a look if so. 😄

**Comment by JRG-Developer** [comment]
Closing due to lack of response.

If you're still having an issue here, please provide a demo project link and/or PR, and I'll re-open.
