### ISSUE TITLE
Latest release breaks scrollView behavior

### ISSUE THREAD

**Issue by benguild** [JRG-Developer/AutoLayoutTextViews#7]
Hi, see please attached. When scrolling to the `AutoLayoutTextView`, the scroll glitches out now perhaps due to the tweaked animation delay behavior. This didn't happen before and we're now pinned at a prior commit. 

https://www.dropbox.com/s/mshdf03fn6gujdr/AutoLayoutTextView%20scrollView%20bug.mov?dl=0

**Comment by JRG-Developer** [comment]
I'm happy to take a look, but I'm having trouble reproducing this issue. I haven't run across this problem in my own apps.

Can you provide a simple demo project that reproduces the issue?

**Comment by JRG-Developer** [comment]
Closed due to no response
